### ISSUE TITLE
Rayman(SLUS00005) unknown opcode

### ISSUE THREAD

**Issue by ZachCook** [pcercuei/lightrec#5]
WARNING: Unknown opcode: 0x00001770 at PC 0x80166518
WARNING: Unknown opcode: 0x00001770 at PC 0x80130c80
WARNING: Unknown opcode: 0x00001770 at PC 0x80130cb4
WARNING: Unknown opcode: 0x00001770 at PC 0x80130ce4
WARNING: Unknown opcode: 0x00001770 at PC 0x80130d34
WARNING: Unknown opcode: 0x00001770 at PC 0x80130d7c
WARNING: Unknown opcode: 0x00001770 at PC 0x801321a0

**Comment by pcercuei** [comment]
Does it crash after? Or the game keeps running?

Also, a bit more info would be great, for instance, how to trigger the bug...

**Comment by pcercuei** [comment]
Answer to myself: It happens right before the Ubisoft logo, and the game keeps running fine.

**Comment by pcercuei** [comment]
This opcode is a "Trap on greater or equal". It is safe to assume that these opcodes are never executed, as they would cause the PSX to crash. They are just leftover debug paths, probably to check div-by-zero. Some games even use bogus opcodes, e.g. Tomb Raider 5 which uses a ```0xdeadbeef``` opcode, just to crash the PSX in case it's executed.

Lightrec will issue a warning when it sees unknown opcodes, but since these are dead code, I think it is safe to simply ignore them.
